version: '0.1.{build}'
image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

install:
  # Install repo specific stuff here

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/AppVeyorClient/AppVeyorClient.csproj --verbosity m

build_script:
  # output will be in ./src/AppVeyorClient/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./src/AppVeyorClient/AppVeyorClient.csproj
  
after_build:
  # For once the build has completed
  - cmd: dotnet pack ./src/AppVeyorClient/AppVeyorClient.csproj --output ./src/AppVeyorClient/bin/debug/netcoreapp1.1/publish

artifacts:
 - path: '**\*.nupkg'
   type: NuGetPackage

clone_depth: 1

test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./tests/AppVeyorClient.Tests/AppVeyorClient.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd ./tests/AppVeyorClient.Tests
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  #server:                  # remove to push to NuGet.org
  api_key:
    secure: Jp5g6Py44Rh01e4zCeqOptcHH8wlt3dyCpVPZ+V6bvBoRwvI3W6lMZOeas2x/H4D
  skip_symbols: false
  #symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/